name: Code Quality Check

on:
  pull_request:
    branches: [main]  

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21.5.0' 

      - name: Install dependencies
        working-directory: ./yank/yank_extension
        run: npm ci

      - name: Run ESLint
        working-directory: ./yank/yank_extension
        run: npm run lint

      - name: Check Prettier formatting
        working-directory: ./yank/yank_extension
        run: npx prettier --check .